### ISSUE TITLE
Unable to create 

### ISSUE THREAD

**Issue by bmarkovic** [treelinehq/treeline#11]
Trying to create empty app with CLI results in this error:

    Error: `read` triggered its `doesNotExist` exit: No file exists at the provided `source` path

But it creates quite a bit of the project structure. Still attempting to link the app with the Treeline app (using `treeeline preview`) results in the following error (last CLI prompt shown above):

    ? Which app would you like to link with the current directory? xxxxxxx
    An error occurred while communicating with the Treeline mothership:  { [Error: `read` triggered its `doesNotExist` exit: No file exists at the provided `source` path] code: 'doesNotExist', exit: 'doesNotExist' }
    Sad face.  Please try again later.

Same error after attempting `treeeline lift` later.

Since the error messages weren't all that verbose, I don't really know what to do next. This is an isolated (nodeenv) environment under Ubuntu Trusty x64 running **iojs** v2.4.0 and **npm** 2.13.0, and **treeline** 2.0.4. 

The environment had sails.js in it (and no other modules that aren't dependencies of either treeline and sails). Sails.js version is 0.11.0.

Attempting `salis lift` results in:

    info: Starting app...
    
    fs.js:97
          throw er;
          ^
    Error: ENOENT: no such file or directory, stat '/home/bmarkovic/Devel/sailsplay/myEmptyApp/node_modules/machine'
        at Error (native)
        at Object.fs.statSync (fs.js:849:18)
        at /home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails-build-dictionary/node_modules/include-all/index.js:48:12
        at Array.forEach (native)
        at requireAll (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails-build-dictionary/node_modules/include-all/index.js:44:9)
        at buildDictionary (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails-build-dictionary/index.js:68:14)
        at Function.module.exports.optional (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails-build-dictionary/index.js:160:9)
        at Array.async.auto.nodeModulesFolder (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails/lib/hooks/moduleloader/index.js:379:27)
        at /home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/async/lib/async.js:487:38
        at Array.forEach (native)
        at _each (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/async/lib/async.js:46:24)
        at Object.async.auto (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/async/lib/async.js:458:9)
        at Hook.loadUserHooks (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails/lib/hooks/moduleloader/index.js:363:13)
        at Hook.bound [as loadUserHooks] (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
        at Hook.initialize (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails/lib/hooks/userhooks/index.js:29:18)
        at Hook.bound [as initialize] (/home/bmarkovic/Devel/sailsplay/lib/node_modules/treeline/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)

**Comment by samuelwight** [comment]
Having the same problem. Please help.

**Comment by particlebanana** [comment]
Hey guys what version of the CLI do you get when you run `treeline -v`?

**Comment by samuelwight** [comment]
CLI v. 2.1.0

**Comment by sgress454** [comment]
Hey y'all, sorry for the delay.  Just FYI you'll have better luck with support for Treeline if you use the in-app Intercom (the big question-mark-in-a-circle in the lower-right corner of the site).  

This was due to a case-sensitivity issue that popped back up in the last version.  I just published v2.1.1 which should fix the issue.
